from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime
import os


class ReportAgent:

    def __init__(self):

        self.output_folder = "reports"

        os.makedirs(self.output_folder, exist_ok=True)

        self.styles = getSampleStyleSheet()

    def generate_report(self, threats, ai_analysis):

        filename = f"Security_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

        filepath = os.path.join(self.output_folder, filename)

        doc = SimpleDocTemplate(filepath)

        story = []

        # ------------------------------------
        # Title
        # ------------------------------------

        story.append(
            Paragraph(
                "<b><font size=18>SentinelAI Security Incident Report</font></b>",
                self.styles["Title"]
            )
        )

        story.append(Spacer(1,20))

        # ------------------------------------
        # Date
        # ------------------------------------

        story.append(
            Paragraph(
                f"<b>Date:</b> {datetime.now()}",
                self.styles["Normal"]
            )
        )

        story.append(Spacer(1,15))

        # ------------------------------------
        # AI Analysis
        # ------------------------------------

        story.append(
            Paragraph(
                "<b>Executive Summary</b>",
                self.styles["Heading2"]
            )
        )

        story.append(
            Paragraph(
                ai_analysis.replace("\n","<br/>"),
                self.styles["Normal"]
            )
        )

        story.append(Spacer(1,20))

        # ------------------------------------
        # Threat Details
        # ------------------------------------

        story.append(
            Paragraph(
                "<b>Detected Threats</b>",
                self.styles["Heading2"]
            )
        )

        if len(threats)==0:

            story.append(
                Paragraph(
                    "No threats detected.",
                    self.styles["Normal"]
                )
            )

        else:

            for threat in threats:

                text = ""

                for key,value in threat.items():

                    text += f"<b>{key}</b>: {value}<br/>"

                story.append(
                    Paragraph(
                        text,
                        self.styles["Normal"]
                    )
                )

                story.append(Spacer(1,10))

        # ------------------------------------
        # Footer
        # ------------------------------------

        story.append(Spacer(1,25))

        story.append(
            Paragraph(
                "<b>Generated by SentinelAI</b>",
                self.styles["Heading3"]
            )
        )

        doc.build(story)

        return filepath


# ----------------------------------------
# Testing
# ----------------------------------------

if __name__=="__main__":

    threats = [

        {
            "Threat":"Brute Force",
            "Severity":"High",
            "IP":"192.168.1.20"
        },

        {
            "Threat":"SQL Injection",
            "Severity":"Critical",
            "IP":"10.0.0.5"
        }

    ]

    analysis = """

Multiple high severity attacks were detected.

Immediate action is recommended.

Block suspicious IPs.

Enable MFA.

Review authentication logs.

"""

    report = ReportAgent()

    pdf = report.generate_report(
        threats,
        analysis
    )

    print(pdf)